"""Backup coding agent (OpenCode) — daily model pick from the free providers listed
in github.com/open-free-llm-api/awesome-freellm-apis (see README_URL for why this
replaced cheahjs/free-llm-api-resources on 2026-08-08).

The repo's README is generated by a script and has TWO provider tables: one for
permanently-free tiers and one for renewable credits. Only the PERMANENT one counts
here — credits are not a free tier. The ORDER inside it is the repo's own (widest
free catalogue first) and it changes as providers come and go, so it is re-read
every morning instead of being hardcoded, and only the top TOP_N_PROVIDERS compete.

What the repo does and does not give us:
  * gives: which providers, in what order, their base URLs, and up to three models
    each with per-model rate limits;
  * does NOT give the FULL model list per provider — only the three best. The rest
    comes from each provider's own /models. Formats differ wildly:
    OpenRouter lists models as markdown links (ids extractable), Google AI Studio
    ships an HTML <table> of display names + per-model limits (no ids at all), and
    NVIDIA NIM lists nothing but "Various open models".
So the model list comes from each provider's OWN OpenAI-compatible /models
endpoint, with the repo (and each provider's pricing) deciding what counts as free.

Strength: OpenRouter publishes benchmarks.artificial_analysis.coding_index, which
is a far better "strongest for coding" signal than a hand-tuned table; where that
is missing we fall back to the local strength table and then to a parameter-count
heuristic. The FINAL choice between providers is by measured SPEED, since anything
that survives the strength step is strong enough to write code.
"""
import json, os, re, time, urllib.error, urllib.parse, urllib.request

from router_lib import CTX, ENVF, HOME, ROOT, UA, get_json

# The provider list moved here on 2026-08-08 (Sergiy's call). The old source,
# cheahjs/free-llm-api-resources, started returning 404 — its README was gone,
# and the router had been silently falling back to Zen for days as a result.
#
# The new repo is machine-readable in a way the old one was not: the tables sit
# between HTML markers (BEGIN_PERMANENT_FREE / BEGIN_QUICK_REF / BEGIN_BEST_MODELS)
# and carry base URLs and per-model rate limits as data instead of prose. Two
# consequences worth knowing:
#   * Ordering is by NUMBER of free models, not by how generous the limits are the
#     way cheahjs sorted his list. "Top 3" now means "widest free catalogue".
#   * OpenRouter moved OUT of the permanently-free table into "Renewable Credits",
#     so it no longer enters the rotation — same rule as the old trial-credits
#     section: credits are not a free tier.
README_URL = ("https://raw.githubusercontent.com/open-free-llm-api/"
              "awesome-freellm-apis/main/README.md")
# Written into providers-seen.json so a future source change is recognised as
# such instead of announcing all 30 providers as brand new.
README_SOURCE_ID = "open-free-llm-api/awesome-freellm-apis"

# The secrets file Sergiy fills in when the bot asks for a missing key. Kept apart
# from ~/.hermes/.env (Hermes' own runtime env) so third-party model keys have one
# obvious home; both are read, this one wins.
SECRETS = f"{HOME}/.hermes/ai-models.env"
HISTORY = f"{ROOT}/coder-history.json"

# One entry per provider that can appear in the repo's FREE section. `env` lists
# every alias models.dev knows for that provider's key, so a key already present
# under any common name is found instead of asked for again.
PROVIDERS = {
    "OpenRouter": {
        "id": "openrouter", "base": "https://openrouter.ai/api/v1",
        "env": ["OPENROUTER_API_KEY"], "signup": "https://openrouter.ai/keys"},
    "Google Gemini": {
        "id": "google",
        "base": "https://generativelanguage.googleapis.com/v1beta/openai",
        "env": ["GOOGLE_API_KEY", "GOOGLE_GENERATIVE_AI_API_KEY", "GEMINI_API_KEY",
                "OPENAI_API_KEY"],
        "signup": "https://aistudio.google.com/app/apikey"},
    "NVIDIA NIM": {
        "id": "nvidia", "base": "https://integrate.api.nvidia.com/v1",
        "env": ["NVIDIA_API_KEY"], "signup": "https://build.nvidia.com"},
    "ModelScope": {
        # Alibaba's model hub. Second-widest free catalogue in the repo (55 models)
        # and OpenAI-compatible, so the generic path handles it as-is.
        #
        # Gotcha worth keeping: /v1/models answers 200 WITHOUT a valid token, while
        # /v1/chat/completions 401s — so "the catalogue loaded" proves nothing about
        # the key.
        #
        # Deliberately the .ai host, not the .cn one the repo lists. Both serve the
        # same catalogue, but on a rejected key .cn says only "Authentication
        # failed, please make sure that a valid ModelScope token is supplied" —
        # which sends you hunting for a bad key — while .ai states the real reason:
        # "Please bind your Alibaba Cloud account before use"
        # (modelscope.ai/my/settings/account). The token is perfectly valid in that
        # state; the free quota simply is not switched on yet. A provider that
        # explains its own refusal is worth more than one that does not.
        "id": "modelscope", "base": "https://api-inference.modelscope.ai/v1",
        "env": ["MODELSCOPE_API_KEY", "MODELSCOPE_SDK_TOKEN"],
        "signup": "https://modelscope.cn/my/myaccesstoken"},
    "Mistral AI": {
        "id": "mistral", "base": "https://api.mistral.ai/v1",
        "env": ["MISTRAL_API_KEY"], "signup": "https://console.mistral.ai/api-keys"},
    "Mistral (Codestral)": {
        "id": "mistral", "base": "https://codestral.mistral.ai/v1",
        "env": ["CODESTRAL_API_KEY", "MISTRAL_API_KEY"],
        # This endpoint serves /chat/completions but has NO /models (404), so the
        # generic "ask the provider" path finds nothing. The ids are fixed anyway.
        "models": ["codestral-latest", "codestral-2508"],
        "signup": "https://console.mistral.ai/codestral"},
    "Cerebras": {
        "id": "cerebras", "base": "https://api.cerebras.ai/v1",
        "env": ["CEREBRAS_API_KEY"], "signup": "https://cloud.cerebras.ai"},
    "Groq": {
        "id": "groq", "base": "https://api.groq.com/openai/v1",
        "env": ["GROQ_API_KEY"], "signup": "https://console.groq.com/keys"},
    "Cohere": {
        "id": "cohere", "base": "https://api.cohere.ai/compatibility/v1",
        "env": ["COHERE_API_KEY"], "signup": "https://dashboard.cohere.com/api-keys"},
    "Hugging Face": {
        "id": "huggingface", "base": "https://router.huggingface.co/v1",
        "env": ["HF_TOKEN", "HUGGINGFACE_API_KEY"],
        "signup": "https://huggingface.co/settings/tokens"},
    "Vercel AI Gateway": {
        "id": "vercel", "base": "https://ai-gateway.vercel.sh/v1",
        "env": ["AI_GATEWAY_API_KEY", "VERCEL_AI_GATEWAY_KEY"],
        "signup": "https://vercel.com/ai-gateway"},
    "Kilo Code": {
        "id": "kilo", "base": "https://api.kilo.ai/api/gateway",
        "env": ["KILO_API_KEY"], "signup": "https://kilo.ai/docs/gateway"},
    "OpenCode Zen": {
        "id": "opencode", "base": "https://opencode.ai/zen/v1",
        "env": ["OPENCODE_ZEN_API_KEY"], "signup": "https://opencode.ai/zen"},
    "Cloudflare Workers AI": {
        # The only provider whose base URL is not a constant: the account id sits
        # in the path, so `base` is a template filled by ensure_base() once a key
        # is in hand. The OpenAI-compatible surface lives under /ai/v1 and serves
        # /chat/completions — but NOT GET /models (405), which is why there is a
        # dedicated listing branch in list_free_models.
        #
        # The account id is looked up from CLOUDFLARE_ACCOUNT_ID, or discovered
        # through /accounts with the same token. Note that account-scoped tokens
        # (cfat_…) fail /user/tokens/verify with "Invalid API Token" while working
        # perfectly everywhere else — do not use that endpoint to judge the key.
        "id": "cloudflare-workers-ai",
        "base": "https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/v1",
        "account_env": ["CLOUDFLARE_ACCOUNT_ID"],
        "env": ["CLOUDFLARE_API_KEY", "CLOUDFLARE_API_TOKEN"],
        "signup": "https://dash.cloudflare.com/profile/api-tokens"},
}

# The single coding task every candidate gets, so the timings are comparable.
# Deliberately small and deterministic: enough output to measure tokens/sec, not
# so much that a slow provider blows the morning budget.
CODING_PROMPT = ("Write one self-contained HTML file: a contact form with exactly "
                 "10 labelled input fields and a submit button. Output only code, "
                 "no explanation.")

# Probe budget. 4000 tokens was not enough for heavy reasoning models: glm-5.2,
# deepseek-v4-pro and nemotron-3-ultra spent the whole budget thinking and stopped
# mid-form, so they were rejected for the wrong reason. 8000 lets them finish; the
# timeout has to grow with it or they simply time out instead (they generate at
# ~47 tok/s, so 8000 tokens needs ~170s). Both env-overridable, because the pair
# is the main lever on how long the morning run takes.
PROBE_MAX_TOKENS = int(os.environ.get("HERMES_PROBE_MAX_TOKENS", "8000"))
PROBE_TIMEOUT_S = int(os.environ.get("HERMES_PROBE_TIMEOUT_S", "190"))

# Time is bounded per provider instead of per candidate: with a long timeout, three
# dead candidates would otherwise cost ~10 minutes on ONE provider — unacceptable
# once every provider in the list has a key.
PROVIDER_BUDGET_S = int(os.environ.get("HERMES_PROVIDER_BUDGET_S", "300"))
# And the whole coder stage is capped, so a list that grows to a dozen providers
# cannot turn the 07:00 job into an hour-long one. Providers not reached are
# reported as such rather than silently skipped.
CODER_STAGE_BUDGET_S = int(os.environ.get("HERMES_CODER_STAGE_BUDGET_S", "1500"))

# Where to run the end-to-end check of the chosen backup agent. MUST be a git repo:
# `opencode run` outside a project prints nothing and exits 0.
VERIFY_DIR = os.environ.get(
    "HERMES_OPENCODE_VERIFY_DIR",
    "/srv/sergiy_prod/ai-agents-config")
OPENCODE_BIN = os.environ.get("HERMES_OPENCODE_BIN", f"{HOME}/.opencode/bin/opencode")


# Failure texts that mean "never going to work with this agent" — no point retrying.
_HARD_FAIL = ("request too large", "too large for model", "context length",
              "not supported", "unsupported", "invalid api key", "unauthorized",
              "insufficient balance", "payment required", "quota")


def _subprocess_env():
    """os.environ plus every VAR=value in ai-models.env (existing vars win).

    Parsed with the same dumb rules the rest of this module uses — no export
    keywords, no interpolation — because that file is written by hand and by the
    router, never sourced by a shell."""
    env = dict(os.environ)
    try:
        for line in open(SECRETS, encoding="utf-8"):
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            k, v = k.strip(), v.strip().strip('"\'')
            if k and v and k not in env:
                env[k] = v
    except OSError:
        pass
    return env


def verify_backup_agent(timeout=180, retries=1, pause_s=None):
    """Run the REAL CLI and demand a real answer.

    The API probe is not representative of an agent turn: it sends ~30 tokens, while
    OpenCode ships a ~38k-token system prompt. Groq's free tier caps at 8000 tokens
    PER MINUTE, so gpt-oss-120b sailed through the probe at 435 tok/s and then failed
    every actual request with "Request too large ... TPM Limit 8000". Only running the
    thing catches that class of limit, so the winner is confirmed before it is kept.

    Two requests at most, VERIFY_PAUSE_S apart. An EMPTY answer is what a swallowed
    429 looks like, and it is easy to cause ourselves — the coding probe just spent
    quota on this very model, and Google's free flash-lite allows 15 requests per
    MINUTE. Structural failures (TPM too large, bad key) are not retried at all.

    The 5s gap does not by itself clear a per-minute window; what keeps the pressure
    off is the small number of checks (VERIFY_TOP_N=2) plus skipping the check
    entirely when the winner is the coder already running and already proven.

    Returns {ok, detail}."""
    import subprocess, time as _t
    pause_s = VERIFY_PAUSE_S if pause_s is None else pause_s
    if not os.path.isdir(os.path.join(VERIFY_DIR, ".git")):
        return {"ok": None, "detail": f"{VERIFY_DIR} не git-репозиторий — проверка пропущена"}
    for attempt in range(retries + 1):
      if attempt:
          _t.sleep(pause_s)          # cross the provider's per-minute window
      try:
          # Through a SHELL on purpose. Executed directly as an argv list the CLI
          # prints its header and exits 0 with NO answer, while the identical
          # command via bash returns BACKUP-OK in ~2s (measured both ways). A shell
          # is also how Hermes actually launches it — its terminal tool — so this
          # mirrors reality instead of testing a path nobody uses.
          import shlex
          cmd = (f"{shlex.quote(OPENCODE_BIN)} run "
                 f"{shlex.quote('Reply with exactly: BACKUP-OK')}")
          # -c, not -lc: sourcing the login profile made this hang for the full
          # timeout on one run. A plain shell keeps the behaviour that works
          # without dragging in profile scripts.
          # Hand the subprocess everything in ai-models.env. models.dev builds some
          # providers' base URLs out of env vars (Cloudflare's is
          # .../accounts/${CLOUDFLARE_ACCOUNT_ID}/ai/v1), and a systemd --user unit
          # inherits none of them — so without this the verification of such a
          # provider fails for a reason that has nothing to do with the model.
          r = subprocess.run(["bash", "-c", cmd],
                             cwd=VERIFY_DIR, capture_output=True, text=True,
                             env=_subprocess_env(), timeout=timeout)
      except subprocess.TimeoutExpired:
          # Transient by nature (slow model, provider queue) — let the retry decide,
          # and never record it as a structural verdict.
          detail = f"не ответил за {timeout}с"
          if attempt >= retries:
              return {"ok": False, "detail": detail, "hard": False}
          continue
      except Exception as e:
          return {"ok": False, "detail": str(e)[:80]}
      # The CLI colourises its output; raw escapes would land in the Telegram report.
      out = re.sub(r"\x1b\[[0-9;]*m", "", (r.stdout or "") + (r.stderr or ""))
      if "BACKUP-OK" in out:
          return {"ok": True, "detail": "" if not attempt else f"со 2-й попытки"}
      # Surface the provider's own complaint — that is where TPM/quota errors live.
      err = next((ln.strip() for ln in out.splitlines()
                  if "rror" in ln or "imit" in ln), "")
      detail = (err or "пустой ответ")[:120]
      if any(w in detail.lower() for w in _HARD_FAIL):
          return {"ok": False, "detail": detail, "hard": True}
    return {"ok": False, "detail": detail + " (и со 2-й попытки)", "hard": False}


# Providers seen in the repo so far — a name that is not in here is NEW, which is
# the signal to ask Sergiy to register and add a key.
SEEN_PROVIDERS = f"{ROOT}/providers-seen.json"
# Which refs have actually driven the agent, and which never could. Without this the
# pick thrashes: a model that fails the agent test every single day keeps being tried
# first because it is the fastest on the API probe.
VERIFIED = f"{ROOT}/coder-verified.json"
# How many candidates get a LIVE check, and how long between the two attempts.
# Deliberately small: each check is a full agent turn (~38k-token system prompt), so
# five candidates x two attempts meant up to ten heavy requests back to back — which
# is what tripped the providers' per-minute quotas and made healthy models look dead.
VERIFY_TOP_N = int(os.environ.get("HERMES_VERIFY_TOP_N", "2"))
VERIFY_PAUSE_S = int(os.environ.get("HERMES_VERIFY_PAUSE_S", "5"))


def load_verified():
    try:
        return json.load(open(VERIFIED))
    except Exception:
        return {}


def save_verified(v):
    json.dump(v, open(VERIFIED, "w"), indent=2, ensure_ascii=False)


# A negative verdict EXPIRES. Per-minute quotas make false negatives easy to
# collect — a model that failed while five agent turns were fired back to back can
# be perfectly healthy tomorrow — and a permanent ok:False would bury it forever.
# A positive verdict does not expire: proven-once is a good enough reason to try
# first, and if it broke, today's check demotes it.
NEGATIVE_TTL_DAYS = int(os.environ.get("HERMES_VERIFY_NEGATIVE_TTL_DAYS", "3"))


def _fresh(rec, today=None):
    try:
        import datetime as _dt
        d = _dt.date.fromisoformat(rec.get("date", ""))
        now = _dt.date.fromisoformat(today) if today else _dt.date.today()
        return (now - d).days < NEGATIVE_TTL_DAYS
    except Exception:
        return False


def verify_rank(v, ref, today=None):
    """Sort key: proven refs first, never-tried (or stale-negative) next, known-broken
    last, structurally-impossible refs dead last.

    A STRUCTURAL failure is sticky for the TTL and a later success does not clear it.
    Groq's gpt-oss-120b earned that rule: its free tier caps at 8000 tokens/minute
    while one agent turn is ~38k, so it cannot work — yet it answered exactly once,
    which was enough for a single-shot check to crown it and write a broken coder
    into the config. One success cannot outvote physics."""
    rec = v.get(ref)
    if not rec:
        return 1                     # unknown — worth a try
    if rec.get("hard") and _fresh(rec, today):
        return 3
    if rec.get("ok"):
        return 0
    try:
        import datetime as _dt
        d = _dt.date.fromisoformat(rec.get("date", ""))
        now = _dt.date.fromisoformat(today) if today else _dt.date.today()
        if (now - d).days >= NEGATIVE_TTL_DAYS:
            return 1                 # stale failure — give it another chance
    except Exception:
        pass
    return 2


def load_seen():
    """Provider names seen on a previous run — empty set means "announce nothing".

    Returns empty ALSO when the record was written against a different source
    repo. Otherwise the day the source changes, every provider in the new list
    counts as brand new and Sergiy gets a Telegram wall of 30 registration
    requests — none of which are actually news."""
    try:
        d = json.load(open(SEEN_PROVIDERS))
    except Exception:
        return set()
    if d.get("source") != README_SOURCE_ID:
        return set()
    return set(d.get("providers", []))


def save_seen(names):
    json.dump({"source": README_SOURCE_ID, "providers": sorted(names)},
              open(SEEN_PROVIDERS, "w"), indent=2, ensure_ascii=False)


# --------------------------------------------------------------------------- repo
def fetch_readme(timeout=30):
    req = urllib.request.Request(README_URL)
    req.add_header("User-Agent", UA)
    with urllib.request.urlopen(req, timeout=timeout, context=CTX) as r:
        return r.read().decode("utf-8", "replace")


def _marked_block(md, name):
    """Text between <!-- BEGIN_name --> and <!-- END_name -->, or ''.

    The repo maintains these tables with a generator and the markers are what it
    writes them between, so they are the most stable handle in the file — far more
    stable than the emoji headings above them ('### ⚡ Permanent Free Tiers')."""
    start = md.find(f"<!-- BEGIN_{name} -->")
    if start < 0:
        return ""
    end = md.find(f"<!-- END_{name} -->", start)
    return md[start:end if end > 0 else len(md)]


def _table_rows(block):
    """Markdown table rows as lists of stripped cells, header/separator dropped."""
    rows = []
    for line in block.splitlines():
        line = line.strip()
        if not line.startswith("|"):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if not cells or set("".join(cells)) <= set("-: "):
            continue                              # separator row
        rows.append(cells)
    return rows[1:] if rows else []               # drop the header row


def _first_href(cell):
    m = re.search(r'href="([^"]+)"', cell or "")
    return m.group(1) if m else ""


def parse_free_section(md):
    """Ordered [{name, url, limits, base, table, model_links}] — free tiers only.

    Source of truth is the PERMANENT_FREE table, in the repo's own order. The
    RENEWABLE table is deliberately ignored: those providers renew a credit
    balance rather than serving free models, which is the same reason the old
    source's trial-credits section never entered the rotation. OpenRouter now
    lives there.

    Two more tables are folded into each entry because the coder pick needs them:
      * QUICK_REF   → the provider's base URL (used only as a fallback; a base we
                      have hardcoded and probed beats one parsed out of a README).
      * BEST_MODELS → up to three model ids with their own rate limits. This is
                      what `limits` and `table` are built from, so the per-model
                      requests/day gate keeps working now that the provider-level
                      '**Limits:**' prose is gone.
    """
    rows = _table_rows(_marked_block(md, "PERMANENT_FREE"))
    if not rows:
        return []

    bases = {}
    for r in _table_rows(_marked_block(md, "QUICK_REF")):
        if len(r) >= 2:
            bases[r[0]] = r[1].strip().strip("`")

    # BEST_MODELS repeats the provider name only on its first row; the following
    # rows leave that cell empty and belong to the same provider.
    best, current = {}, None
    for r in _table_rows(_marked_block(md, "BEST_MODELS")):
        if len(r) < 5:
            continue
        name, _disp, mid, ctx, lim = r[0], r[1], r[2].strip().strip("`"), r[3], r[4]
        if name:
            current = name
        if not current or not mid:
            continue
        best.setdefault(current, []).append({"id": mid, "ctx": ctx, "limits": lim})

    out = []
    for r in rows:
        if len(r) < 2:
            continue
        name = r[0]
        models = best.get(name, [])
        # The provider-level limit is the strictest thing we know about it: take the
        # first model line that states a real number rather than "See provider".
        lim = next((m["limits"] for m in models if rpd(m["limits"])), "")
        out.append({"name": name, "url": _first_href(r[-1]),
                    "limits": lim,
                    "base": bases.get(name, ""),
                    "free_models": r[1],
                    # Same shape the Google branch of list_free_models expects:
                    # (id, per-model limits). Ids here are real API ids, not display
                    # names, so _match_live_id has an easier job than it used to.
                    "table": [(m["id"], m["limits"]) for m in models],
                    "model_links": []})
    return out


# ------------------------------------------------------------------------- secrets
def _env_files():
    return [SECRETS, ENVF]


def find_key(prov):
    """First value found for any of the provider's key aliases, secrets file first.
    Returns (key, source_path, var_name) or (None, None, None)."""
    for path in _env_files():
        try:
            lines = open(path).read().splitlines()
        except OSError:
            continue
        for var in prov["env"]:
            for line in lines:
                if line.startswith(var + "="):
                    val = line.split("=", 1)[1].strip().strip('"\'')
                    if val:
                        return val, path, var
    return None, None, None


def _env_lookup(names):
    """First non-empty value among *names* across the env files."""
    for path in _env_files():
        try:
            lines = open(path).read().splitlines()
        except OSError:
            continue
        for var in names or ():
            for line in lines:
                if line.startswith(var + "="):
                    val = line.split("=", 1)[1].strip().strip('"\'')
                    if val:
                        return val
    return None


def cloudflare_account_id(key, persist=True):
    """Account id for the Workers AI path: env first, then ask Cloudflare.

    Discovery keeps this from being a second thing Sergiy has to paste by hand —
    the same token that calls the model can list the account it belongs to. The
    answer is written back to the secrets file so tomorrow costs no extra call.

    `persist=False` for --dry-run: that mode promises to touch nothing, and every
    other write in this run is guarded, so appending to a 0600 secrets file the
    operator did not expect to be modified would be the one exception."""
    got = _env_lookup(["CLOUDFLARE_ACCOUNT_ID"])
    if got:
        return got
    d = get_json("https://api.cloudflare.com/client/v4/accounts", key, timeout=30)
    accounts = d.get("result") or []
    if not accounts:
        raise RuntimeError("токен не видит ни одного аккаунта Cloudflare")
    acc = accounts[0].get("id")
    if acc and len(accounts) == 1 and persist:
        try:
            with open(SECRETS, "a") as f:
                f.write(f"\n# Найден автоматически по токену — путь Workers AI\n"
                        f"CLOUDFLARE_ACCOUNT_ID={acc}\n")
        except OSError:
            pass
    return acc


def ensure_base(prov, key, persist=True):
    """Fill a templated base URL in place. No-op for ordinary providers.

    Returns the resolved base, or raises so the caller reports the provider as
    unusable instead of probing a URL with a literal '{account_id}' in it."""
    base = prov.get("base") or ""
    if "{account_id}" not in base:
        return base
    acc = cloudflare_account_id(key, persist=persist)
    if not acc:
        raise RuntimeError("не удалось определить CLOUDFLARE_ACCOUNT_ID")
    prov["base"] = base.replace("{account_id}", acc)
    # Remembered so the OpenCode config gets an explicit baseURL for this provider:
    # a templated base means models.dev cannot build the URL without an env var the
    # CLI may not have. See set_opencode_model.
    prov["_base_templated"] = True
    return prov["base"]


def _error_message(body):
    """The human-readable reason out of an error body, whatever shape it came in.

    OpenAI-style providers use {"error": {"message": ...}}. Cloudflare uses
    {"errors": [{"message": ...}], "success": false} — plural, and a LIST. Reading
    only the singular form dropped Cloudflare's text entirely and left a bare
    "HTTP 403", which is how its "not available on the Workers Free plan" refusals
    went unrecognised: the phrase the detector looks for was being thrown away
    before the detector ever saw it.
    """
    if not isinstance(body, dict):
        return ""
    err = body.get("error")
    if isinstance(err, dict) and err.get("message"):
        return str(err["message"])
    if isinstance(err, str) and err:
        return err
    errs = body.get("errors")
    if isinstance(errs, list):
        for e in errs:
            if isinstance(e, dict) and e.get("message"):
                return str(e["message"])
            if isinstance(e, str) and e:
                return e
    return str(body.get("message") or "")


# A model that the account's plan does not include answers instantly (~150 ms)
# and will answer the same way tomorrow. It must not consume one of the few
# probe attempts a provider gets — see the walk in refresh.py.
_PLAN_LOCKED = ("not available on the workers free plan", "upgrade to access",
                "requires a paid plan", "insufficient balance")


def plan_locked(err):
    low = (err or "").lower()
    return any(s in low for s in _PLAN_LOCKED)


def ensure_secrets_file():
    """Create ~/.hermes/ai-models.env with a header the first time, 0600."""
    import os
    if os.path.exists(SECRETS):
        return False
    os.umask(0o077)
    with open(SECRETS, "w") as f:
        f.write("# Secrets for third-party FREE model providers.\n"
                "# The daily model-router asks for whatever is missing here (Telegram);\n"
                "# add the key as VAR=value and it is picked up next morning.\n"
                "# One var per provider, names match models.dev.\n")
    os.chmod(SECRETS, 0o600)
    return True


# -------------------------------------------------------------------- model lists
def _params_from_id(mid):
    """Crude size signal: '...-550b-a55b' -> 550. Used only when nothing better."""
    m = re.findall(r'(\d+(?:\.\d+)?)b\b', mid.lower())
    return max((float(x) for x in m), default=0.0)


# Not coding models — they show up in the same free lists and would otherwise win
# on size alone. A TTS or image model cannot write an HTML form.
_NOT_CODERS = ("tts", "-audio", "audio-", "image", "-vision-only", "robotics",
               "content-safety", "embed", "-live", "guard", "rerank", "whisper",
               "moderation", "-ocr")


def _is_coder(mid):
    low = mid.lower()
    return not any(w in low for w in _NOT_CODERS)


def _match_live_id(display, live):
    """Repo display name -> real API id.

    The repo prints human names ('Gemini 3 Flash', 'Gemma 4 31B Instruct') while
    the API serves ids with suffixes and abbreviations ('gemini-3-flash-preview',
    'gemma-4-31b-it'). Try the obvious transforms, then a prefix match, and give up
    rather than guess a name that does not exist."""
    cand = display.strip().lower().replace(" ", "-")
    variants = [cand, cand + "-preview", cand + "-latest",
                cand.replace("-instruct", "-it"),
                cand.replace("-instruct", "-it") + "-preview"]
    for v in variants:
        if v in live:
            return v
    pref = [m for m in live if m.startswith(cand + "-")]
    return sorted(pref, key=len)[0] if pref else None


# A coding agent spends many requests on one task (read files, edit, re-read,
# verify), so a model with 20 requests/day is unusable no matter how strong it is.
# Anything at or above this floor counts as "workable limits".
MIN_RPD = 100


def rpd(limits):
    """Requests/day stated in the repo's limits text, or None if not stated.

    Two spellings, because the source changed: the old repo wrote it out
    ('1,000 requests/day'), the new one abbreviates ('1,500 RPD', '2,000 RPD
    total; <=500 ...'). Deliberately NOT matching 'neurons/day' or other
    non-request budgets — those are a different currency and guessing a request
    count from them would silently gate the wrong providers out."""
    text = limits or ""
    m = re.search(r'([\d,]+)\s*requests?\s*/\s*day', text, re.I)
    if not m:
        m = re.search(r'([\d,]+)\s*RPD\b', text, re.I)
    return int(m.group(1).replace(",", "")) if m else None


def _rank(cands):
    """Strongest-first, WITHOUT mixing incompatible scales.

    OpenRouter's coding_index (~20-60) and the local strength table (~55-90) are
    different scales; ranking them together would hand the win to whichever model
    merely lacked a benchmark. So when any candidate carries a published
    coding_index, only those compete."""
    for c in cands:
        d = rpd(c.get("limits", ""))
        c["rpd"] = d
        # Unstated limits are treated as workable: most providers publish a
        # per-minute cap only, and refusing those would empty the pool.
        c["limits_ok"] = (d is None) or (d >= MIN_RPD)
    benched = [c for c in cands if c["score_src"] == "coding_index"]
    pool = benched if benched else cands
    # Workable limits first, then strength: the strongest model in the world is
    # useless to an agent that gets 20 requests a day.
    pool.sort(key=lambda r: (not r["limits_ok"], -r["score"], r["id"]))
    rest = sorted((c for c in cands if c not in pool),
                  key=lambda r: (not r["limits_ok"], -r["score"], r["id"]))
    return pool + rest


def list_free_models(prov, key, repo_entry, strength_table, default_strength):
    """Normalized free-model candidates for one provider.

    [{id, ctx, score, score_src, limits}] — ordered strongest-first.
    """
    pid, base = prov["id"], prov["base"]
    out = []

    if pid == "openrouter":
        # OpenRouter's own API is authoritative AND carries coding benchmarks.
        d = get_json(f"{base}/models", timeout=30)
        for m in d.get("data", []):
            mid = m.get("id", "")
            pricing = m.get("pricing") or {}
            is_free = mid.endswith(":free") or float(pricing.get("prompt", 1) or 0) == 0
            if not is_free or not _is_coder(mid):
                continue
            ci = (((m.get("benchmarks") or {}).get("artificial_analysis") or {})
                  .get("coding_index"))
            if ci is not None:
                score, src = float(ci), "coding_index"
            else:
                score, src = _heuristic(mid, strength_table, default_strength)
            out.append({"id": mid, "ctx": m.get("context_length") or 0,
                        "score": round(score, 1), "score_src": src,
                        "limits": repo_entry.get("limits", "")})

    elif pid == "google":
        # The repo's HTML table is the free-tier list; ids come from the live
        # OpenAI-compatible /models so we never invent a name.
        live = {m["id"].split("/")[-1] for m in
                get_json(f"{base}/models", key, timeout=30).get("data", [])}
        for disp, lim in repo_entry.get("table", []):
            mid = _match_live_id(disp, live)
            if not mid or not _is_coder(mid):
                continue
            score, src = _heuristic(mid, strength_table, default_strength)
            out.append({"id": mid, "ctx": 0, "score": round(score, 1),
                        "score_src": src, "limits": lim.replace("<br>", " / ")})

    elif pid == "cloudflare-workers-ai":
        # Workers AI has no OpenAI-style catalogue — GET /ai/v1/models is a 405.
        # Its own models/search does the job and filters to text generation, so the
        # image and speech models never enter the ranking in the first place.
        #
        # It does NOT say which models the account's plan includes: gpt-oss-120b
        # and kimi-k2.7-code look identical here, and only the second one 403s with
        # "not available on the Workers Free plan". Both are listed; the probe walk
        # sorts that out, and plan_locked() keeps the rejects from costing attempts.
        acc = base.rsplit("/ai/v1", 1)[0]
        d = get_json(f"{acc}/ai/models/search?task=Text%20Generation&per_page=100",
                     key, timeout=30)
        for m in d.get("result") or []:
            mid = m.get("name") or ""
            if not mid or not _is_coder(mid):
                continue
            ctx = 0
            for p in m.get("properties") or []:
                if p.get("property_id") == "context_window":
                    try:
                        ctx = int(p.get("value") or 0)
                    except (TypeError, ValueError):
                        ctx = 0
            score, src = _heuristic(mid, strength_table, default_strength)
            out.append({"id": mid, "ctx": ctx, "score": round(score, 1),
                        "score_src": src, "limits": repo_entry.get("limits", "")})

    else:
        # Generic path (NVIDIA NIM and friends): the repo lists no ids, so ask the
        # provider. Everything its free tier exposes is a candidate.
        try:
            d = get_json(f"{base}/models", key, timeout=30)
        except Exception:
            # Some endpoints only serve completions (Codestral 404s on /models).
            fixed = prov.get("models") or []
            if not fixed:
                raise
            d = {"data": [{"id": m} for m in fixed]}
        # OpenCode Zen is the exception: its /models mixes free and PAID models, and
        # the paid ones answer 401 "Insufficient balance" — three wasted probes every
        # morning. models.dev prices them, so keep only the $0 ones.
        free_only = None
        if pid == "opencode":
            try:
                from router_lib import load_catalog
                oc = load_catalog()["opencode"]["models"]
                free_only = {k for k, v in oc.items()
                             if (v.get("cost") or {}).get("input", 1) == 0}
            except Exception:
                free_only = None
        # Does this catalogue distinguish a free subset at all?
        marks_free = any(str(m.get("id", "")).endswith(":free") for m in d.get("data", []))
        for m in d.get("data", []):
            mid = m.get("id", "")
            if not mid or not _is_coder(mid):
                continue
            if free_only is not None and mid not in free_only:
                continue
            # Only filter by price on catalogues that MARK a free subset. Kilo lists
            # 344 models of which 13 carry ":free" — there the price is the signal.
            # Groq publishes list prices for models its FREE tier serves anyway
            # (gpt-oss-120b at 0.00000015/token), so filtering on price there threw
            # away its ten best candidates and kept three unpriced oddities.
            if marks_free:
                pricing = m.get("pricing") or {}
                try:
                    priced = float(pricing.get("prompt", 0) or 0) != 0
                except (TypeError, ValueError):
                    priced = False
                if priced and not mid.endswith(":free"):
                    continue
            score, src = _heuristic(mid, strength_table, default_strength)
            out.append({"id": mid, "ctx": 0, "score": round(score, 1),
                        "score_src": src, "limits": repo_entry.get("limits", "")})

    return _rank(out)


def _heuristic(mid, strength_table, default_strength):
    """(score, source) when no published coding benchmark exists."""
    # Lowercased: HuggingFace serves ids like "zai-org/GLM-5.2" and "moonshotai/
    # Kimi-K3", and the strength table is written in lower case — without this every
    # one of its 129 models fell through to default_strength and "strongest" became
    # whatever sorted first.
    base = mid.split("/")[-1].removesuffix(":free").lower()
    if base in strength_table:
        return float(strength_table[base]), "таблица сил"
    # family match: 'gemini-3.6-flash' -> try progressively shorter prefixes
    parts = base.split("-")
    for n in range(len(parts) - 1, 1, -1):
        if "-".join(parts[:n]) in strength_table:
            return float(strength_table["-".join(parts[:n])]), "таблица сил (семейство)"
    p = _params_from_id(base)
    if p:
        # 9B→~55, 30B→~62, 120B→~70, 550B→~80; log-ish, capped.
        return min(85.0, 45 + 13.0 * (p ** 0.25)), f"эвристика по размеру (~{p:g}B)"
    return float(default_strength), "дефолт"


# ------------------------------------------------------------------------- probing
def coding_probe(prov, key, model, timeout=None, max_tokens=None,
                 _retry_of_truncation=False):
    """Send THE SAME coding task to every candidate and time it.

    Returns {ok, ms, gen_tokens, visible_tokens, tps, chars, inputs, truncated,
    error}.

    Two traps this deliberately avoids, both of which would rank a good provider
    as "slow server":
      * throughput is computed from ALL generated tokens (`total - prompt`), not
        from `completion_tokens`. Reasoning models bill most of their generation to
        hidden thinking: gemini-3.6-flash reported 43 completion tokens for a
        1228-token turn, which reads as 6 tok/s when the truth is ~180.
      * max_tokens is generous (4000). At 1200 the same model spent the whole
        budget thinking and returned a form cut off mid-tag — an unusable sample.
    `ok` also checks the answer IS a form (>=8 inputs), so a model that fails fast
    cannot win a speed contest."""
    timeout = timeout or PROBE_TIMEOUT_S
    max_tokens = max_tokens or PROBE_MAX_TOKENS
    body = json.dumps({"model": model, "max_tokens": max_tokens,
                       "messages": [{"role": "user", "content": CODING_PROMPT}]}).encode()
    req = urllib.request.Request(prov["base"] + "/chat/completions", data=body)
    req.add_header("User-Agent", UA)
    req.add_header("Authorization", "Bearer " + key)
    req.add_header("Content-Type", "application/json")
    t0 = time.monotonic()
    try:
        with urllib.request.urlopen(req, timeout=timeout, context=CTX) as r:
            d = json.loads(r.read())
    except urllib.error.HTTPError as e:
        detail = ""
        try:
            detail = _error_message(json.loads(e.read()))[:120]
        except Exception:
            pass
        # 413 = our max_tokens exceeds what this model accepts per request. That is
        # our setting's fault, not the model's, so try once at half budget before
        # writing off a candidate (this is how Groq's gpt-oss-120b was being lost).
        if (e.code in (400, 413) and max_tokens > 2000
                and ("max_tokens" in detail or e.code == 413)):
            return coding_probe(prov, key, model, timeout=timeout,
                                max_tokens=max_tokens // 2,
                                _retry_of_truncation=_retry_of_truncation)
        return {"ok": False, "ms": int((time.monotonic() - t0) * 1000),
                "error": f"HTTP {e.code} {detail}".strip()}
    except Exception as e:
        return {"ok": False, "ms": int((time.monotonic() - t0) * 1000),
                "error": str(e)[:80]}
    ms = int((time.monotonic() - t0) * 1000)
    if "error" in d:
        return {"ok": False, "ms": ms, "error": str(d["error"])[:80]}
    try:
        choice = d["choices"][0]
        text = (choice["message"].get("content") or "")
    except Exception:
        return {"ok": False, "ms": ms, "error": "нет choices"}
    usage = d.get("usage") or {}
    visible = (usage.get("completion_tokens") or usage.get("output_tokens") or 0)
    total = usage.get("total_tokens") or 0
    prompt = usage.get("prompt_tokens") or usage.get("input_tokens") or 0
    gen = max(total - prompt, visible)          # includes hidden reasoning tokens
    secs = max(ms / 1000.0, 0.001)
    inputs = text.lower().count("<input")
    truncated = choice.get("finish_reason") == "length"
    # Order matters: truncation is checked BEFORE counting fields. Heavy reasoning
    # models (glm-5.2, deepseek-v4-pro, nemotron-3-ultra) spend the whole budget
    # thinking and stop mid-form, and reporting that as "не форма (2 полей)" hides
    # the actual reason — it reads as "answered the wrong thing" when the truth is
    # "cannot finish this inside 4000 tokens", which is itself a fair reason to
    # reject a backup coder.
    if not text.strip():
        err = "пустой ответ"
    elif truncated:
        # Not "N из 10": the count is of <input> tags actually emitted, and a
        # verbose model writes more than ten before running out (one printed
        # "16 из 10"). Report what it managed, not a fraction of the ask.
        err = (f"не уложился в {max_tokens} токенов — reasoning съел бюджет "
               f"(успел {inputs} полей, ответ оборван)")
    elif inputs < 8:
        err = f"не форма ({inputs} полей)"
    else:
        err = ""
    # A truncated answer is our budget's fault as much as the model's: on HuggingFace
    # GLM-5.2 generates at 217 tok/s — three times its speed on NVIDIA — and still
    # ran out mid-form. Give exactly those candidates ONE retry at double budget, so
    # a fast reasoning model is measured instead of written off. Only truncation
    # qualifies; a wrong answer or an empty one is not a budget problem.
    if truncated and max_tokens < 20000 and not _retry_of_truncation:
        return coding_probe(prov, key, model, timeout=int(timeout * 1.5),
                            max_tokens=max_tokens * 2, _retry_of_truncation=True)
    return {"ok": not err, "ms": ms, "gen_tokens": gen, "visible_tokens": visible,
            "tps": round(gen / secs, 1) if gen else None,
            "chars": len(text), "inputs": inputs, "truncated": truncated,
            "error": err}


def declared_speed(prov, key, model):
    """Reference tokens/sec to compare the measurement against.

    OpenRouter publishes rolling 30-minute throughput/latency per endpoint — the
    only provider of the three that does. Returns {tps, latency_ms, source} or
    {} when nobody publishes anything (then refresh.py falls back to our own
    rolling baseline from coder-history.json)."""
    if prov["id"] != "openrouter":
        return {}
    slug = model.removesuffix(":free")
    try:
        d = get_json(f"{prov['base']}/models/{slug}/endpoints", key, timeout=25)
    except Exception:
        return {}
    eps = ((d.get("data") or {}).get("endpoints") or [])
    tps = [v for v in (_p50(e.get("throughput_last_30m")) for e in eps) if v]
    lat = [v for v in (_p50(e.get("latency_last_30m")) for e in eps) if v]
    if not tps:
        return {}
    # Median across endpoints, not the best one: OpenRouter picks the endpoint, so
    # the fastest provider on the list is not what we are promised. Taking the max
    # would make an ordinary run look "slower than declared" every morning.
    return {"tps": round(_median(tps), 1),
            "latency_ms": round(_median(lat), 1) if lat else None,
            "source": "OpenRouter throughput_last_30m (p50, медиана по endpoint-ам)"}


def _p50(val):
    """Pull a number out of OpenRouter's rolling stats.

    With a key these fields are PERCENTILE DICTS
    (`{"p50": 34, "p75": 48, "p90": 65, "p99": 139}`); without one they came back
    as null, which is how a naive `max()` over them shipped and then blew up with
    "'>' not supported between instances of 'dict' and 'dict'" the moment a real key
    was added. Accepts a plain number too, in case the shape changes back."""
    if isinstance(val, (int, float)):
        return float(val)
    if isinstance(val, dict):
        for k in ("p50", "median", "p75", "value"):
            v = val.get(k)
            if isinstance(v, (int, float)):
                return float(v)
        nums = [v for v in val.values() if isinstance(v, (int, float))]
        return float(min(nums)) if nums else None
    return None


def _median(nums):
    s = sorted(nums)
    n = len(s)
    return s[n // 2] if n % 2 else (s[n // 2 - 1] + s[n // 2]) / 2


# ------------------------------------------------------------------------- history
# --- quality scoring over history -------------------------------------------
# One measurement is noise, not evidence. Today's numbers show why: the same
# openrouter/nemotron-3-ultra ranged 14.5 → 80.6 tok/s across ten probes (a 5.5x
# spread), while google/gemini-3.5-flash-lite held 357 → 459 across twelve (±7%).
# Ranking on a single sample means ranking on whose queue happened to be empty.
#
# So the score answers "how bad does it get", not "how good was it once":
#     score = p25(tok/s) × success_rate × (1 − min(CV, 0.5))
# p25 instead of the mean because an agent making dozens of turns lives in the bad
# tail; success_rate because a model that answers half the time is useless however
# fast (glm-5.2 completed the form in 1-2 of 4 attempts); and the CV penalty because
# 400±20 beats 500±300 for anything that has to finish a task.
CV_PENALTY_CAP = 0.5          # never discount by more than half
MIN_SUCCESS_RATE = float(os.environ.get("HERMES_MIN_SUCCESS_RATE", "0.6"))
NEW_MODEL_DISCOUNT = 0.7      # a single sample is worth less than a proven record
HYSTERESIS = float(os.environ.get("HERMES_HYSTERESIS", "1.3"))


def _p25(vals):
    """Pessimistic speed. Few samples → take the worst one seen; the point is to
    stop being seduced by a lucky run."""
    v = sorted(vals)
    if len(v) < 4:
        return v[0]
    import math
    return v[max(0, math.ceil(0.25 * len(v)) - 1)]


def model_stats(hist, ref):
    """{n, ok, success_rate, p25, median, cv, score} over the recorded window."""
    rows = hist.get(ref) or []
    if not rows:
        return None
    # Entries written before the pass/fail flag existed were successes by
    # construction — only wins were logged back then — so a missing key means ok.
    oks = [r for r in rows if r.get("ok", True)]
    tps = [r["tps"] for r in oks if r.get("tps")]
    n, ok = len(rows), len(oks)
    if not tps:
        return {"n": n, "ok": ok, "success_rate": ok / n, "p25": 0.0,
                "median": 0.0, "cv": 0.0, "score": 0.0}
    import statistics as _st
    med = _st.median(tps)
    cv = (_st.stdev(tps) / _st.mean(tps)) if len(tps) > 1 else 0.0
    sr = ok / n
    score = _p25(tps) * sr * (1 - min(cv, CV_PENALTY_CAP))
    return {"n": n, "ok": ok, "success_rate": sr, "p25": _p25(tps),
            "median": med, "cv": cv, "score": score}


def quality_score(hist, ref, today_tps=None):
    """Score used for ranking. Falls back to today's single measurement, discounted,
    so a model we have never seen can still win — but has to win clearly."""
    st = model_stats(hist, ref)
    if st and st["n"] >= 2:
        return st["score"], st
    if today_tps:
        return today_tps * NEW_MODEL_DISCOUNT, st
    return 0.0, st


def record_probe(hist, ref, pr):
    """Every probe goes into the record, PASS OR FAIL — success_rate cannot be
    computed from a log that only kept the wins (which is what it did before)."""
    hist.setdefault(ref, []).append({
        "date": time.strftime("%Y-%m-%d"),
        "ok": bool(pr.get("ok")),
        "ms": pr.get("ms"),
        "tps": pr.get("tps"),
        "err": (pr.get("error") or "")[:60],
    })


def load_history():
    try:
        return json.load(open(HISTORY))
    except Exception:
        return {}


def save_history(hist, keep=14):
    for ref in list(hist):
        hist[ref] = hist[ref][-keep:]
    json.dump(hist, open(HISTORY, "w"), indent=2)


def baseline_tps(hist, ref):
    """Best tokens/sec we have ever measured for this model — our stand-in for a
    'declared' speed when the provider publishes none. Today's number against this
    is what reveals a provider that is merely busy right now."""
    vals = [r.get("tps") for r in hist.get(ref, []) if r.get("tps")]
    return max(vals) if vals else None
