#!/usr/bin/env python3
"""bans-card.py — generate the compact hard-bans card from the detector itself.

WHY
---
The 2026-09-02 pipeline audit (`docs/seo-pipeline-audit-2026-09-02.md`, finding F3) measured
the mechanical style rules as living in four places and being enforced in one:

    brand-assets/style-guides/ai-tells-sweep.md              18,166 B   does not enforce
    brand-assets/content-strategy/terminology-guardrails.md  16,345 B   does not enforce
    brand-assets/style-guides/scripts/detect-ai-tells.py     40,702 B   ENFORCES
    CLAUDE.md section 6                                      inside 46 KB, does not enforce
    plus an inline copy in each of the 4 SEO agent prompts

`seo-writer` and `seo-editor` were each told to read the first two in full, 34,511 B a stage,
to learn rules that the detector was going to check anyway.

The cost of that duplication is not theoretical. When Vadim reverted the "positioned as" rule
on 2026-09-02, the change had to land in the detector, both guardrail docs and twelve agent
prompt files across three copies. The prompts still said `DEXA` after the review had corrected
it to `DXA`, so the writer had to be told to override its own prompt mid-run.

So: the detector's `HARD_EN` patterns and its `CARD` labels are the single source of truth,
and this script renders them into a card an agent can read in one screen. The prose documents
stay for humans, and for the judgment rows no regex can decide.

The card is GENERATED. Never hand-edit it. Edit the detector, then run this.

USAGE
    scripts/bans-card.py                # write the card
    scripts/bans-card.py --check        # exit 1 if the card on disk is stale, print nothing else
    scripts/bans-card.py --stdout       # print, do not write

`--check` is what makes this safe to depend on, the same pattern
`scripts/split-linkedin-prompts.py` uses for the six LinkedIn profile briefs.
"""
from __future__ import annotations

import argparse
import importlib.util
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DETECTOR = os.path.join(REPO, "brand-assets", "style-guides", "scripts", "detect-ai-tells.py")
CARD_PATH = os.path.join(REPO, "brand-assets", "style-guides", "hard-bans-card.md")

BANNER = "<!-- GENERATED by scripts/bans-card.py from detect-ai-tells.py. Do not hand-edit. -->"


def load_detector():
    spec = importlib.util.spec_from_file_location("detect_ai_tells", DETECTOR)
    mod = importlib.util.module_from_spec(spec)
    sys.modules["detect_ai_tells"] = mod
    spec.loader.exec_module(mod)
    return mod


def literal_words(patterns) -> list[str]:
    """Pull the plain banned words out of simple `\\bword(suffix)?\\b` patterns.

    Only the unambiguous shapes. A pattern with alternation across whole phrases, lookarounds
    or character classes is left to its CARD label, because a half-rendered regex in a rule
    card is worse than no example at all.
    """
    out = []
    # `\bleverag(e|es|ed|ing)\b` -> "leverage": the inflection group is REQUIRED, so the bare
    # stem is not a word and printing "leverag" in a rule card looks like a typo. Append the
    # first alternative. An OPTIONAL group (`\bharness(es|ed|ing)?\b`) means the stem itself
    # is the word, so leave it alone.
    pat = re.compile(r"\\b([a-z][a-z' -]*?)(?:\(([a-z|]+)\)(\??))?\\b\Z")
    for p in patterns:
        m = pat.fullmatch(p)
        if not m:
            continue
        stem, group, optional = m.group(1), m.group(2), m.group(3)
        if group and not optional:
            stem += group.split("|")[0]
        out.append(stem)
    return out


def render(mod) -> str:
    hard = mod.HARD_EN
    card = mod.CARD
    lines = [
        BANNER,
        "",
        "# Hard bans, the whole list, one screen",
        "",
        "Every rule here is **mechanically enforced** by",
        "`brand-assets/style-guides/scripts/detect-ai-tells.py`, so a hit is a fix regardless of",
        "density and regardless of how good the sentence is otherwise. Run the gate, do not",
        "trust memory:",
        "",
        "```",
        "python3 scripts/article_lint.py <your-file>.md",
        "```",
        "",
        "This card is generated from the detector's own pattern tables. It cannot drift from",
        "what is enforced, which is the point: read it instead of `ai-tells-sweep.md` (18 KB) and",
        "`terminology-guardrails.md` (16 KB). Those two stay canonical for the **judgment** rows",
        "no regex can decide (corrective negation, corrective \"rather than\", `we/our`, `you`,",
        "vendor blogs as citations) and for the reasoning behind each rule.",
        "",
        f"**{len(hard)} hard categories, {sum(len(v) for v in hard.values())} patterns.**",
        "",
    ]

    for cat in hard:
        rule, fix = card.get(cat, ("(no CARD label, see the detector)", ""))
        lines.append(f"### {cat}")
        lines.append("")
        lines.append(f"{rule}")
        lines.append("")
        if fix:
            lines.append(f"**Instead:** {fix}")
            lines.append("")
        words = literal_words(hard[cat])
        if words:
            lines.append("Literal terms: " + ", ".join(f"`{w}`" for w in sorted(set(words))))
            lines.append("")

    ch = getattr(mod, "CHANNELS", {})
    if ch:
        lines += ["### Channel differences", ""]
        for name, cfg in ch.items():
            mute = cfg.get("mute") or []
            lines.append(f"- `{name}`: mutes {', '.join(mute) if mute else 'nothing'}")
        lines.append("")

    lines += [
        "### The judgment rows this card does NOT cover",
        "",
        "A regex cannot tell a real product boundary from a slight, so these stay human:",
        "corrective negation (`X, not Y`), corrective `rather than`, `we / our` beyond a claim of",
        "ownership, `you` in neutral educational prose, a vendor blog used as a citation, and a",
        "compressed relationship where `depends on` or `varies by` is meant. The editor owns",
        "these. See `brand-assets/content-strategy/terminology-guardrails.md` Part 3, the rows",
        "marked `judgment`.",
        "",
    ]
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true", help="exit 1 if the card on disk is stale")
    ap.add_argument("--stdout", action="store_true", help="print instead of writing")
    args = ap.parse_args()

    mod = load_detector()

    unlabelled = set(mod.HARD_EN) - set(getattr(mod, "CARD", {}))
    if unlabelled:
        print(
            "FAIL: HARD_EN categories with no CARD row: " + ", ".join(sorted(unlabelled)),
            file=sys.stderr,
        )
        print("Add a CARD row in detect-ai-tells.py in the same commit as the pattern.", file=sys.stderr)
        return 1

    content = render(mod)

    if args.stdout:
        sys.stdout.write(content)
        return 0

    if args.check:
        if not os.path.exists(CARD_PATH):
            print(f"FAIL: {os.path.relpath(CARD_PATH, REPO)} does not exist. Run scripts/bans-card.py", file=sys.stderr)
            return 1
        with open(CARD_PATH) as fh:
            on_disk = fh.read()
        if on_disk != content:
            print(
                f"FAIL: {os.path.relpath(CARD_PATH, REPO)} is stale.\n"
                "The detector changed and the card was not regenerated. Run scripts/bans-card.py",
                file=sys.stderr,
            )
            return 1
        print("card is current")
        return 0

    with open(CARD_PATH, "w") as fh:
        fh.write(content)
    print(f"wrote {os.path.relpath(CARD_PATH, REPO)}  ({len(content)} B, "
          f"{len(mod.HARD_EN)} categories)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
