#!/usr/bin/env python3
"""pack-template.py — стабильные секции FitXpress context pack, генерённые кодом.

WHY THIS EXISTS
---------------
Замер прогона Telehealth Documentation (2026-09-21): context-pack-builder
(sonnet) сжёг 173K токенов — больше всех в пайплайне — и ~70% его пака дословно
совпадает с паком предыдущей статьи: compliance-claims, banned_claims,
banned_words, tone, claims_discipline, accuracy_framing, published-инвентарь.
Агент каждый раз заново перечитывал ~200KB канона, чтобы воспроизвести то же
самое, с риском в этот раз что-то не заметить.

Этот скрипт рендерит стабильную часть в
`workspace/seo/_context-packs/_stable-fitxpress.yaml`. context-pack-builder
читает ОДИН этот файл вместо шести канон-источников, вставляет секции verbatim
и работает только над дельтой темы (objective, выбор claims под угол, ICP-срез,
строка контент-плана, синтез ключей).

Почему это безопасно (и когда рендер сам поднимет тревогу):
  * каждый stable-claim несёт `verify`-маркеры — подстроки, которые ОБЯЗАНЫ
    присутствовать в его канон-файле. Канон изменился → рендер падает с
    перечнем, что разъехалось. Тот же приём, что `--check` у bans-card.py и
    split-linkedin-prompts.py;
  * banned_words не написаны руками, а вытащены из detect-ai-tells.py — из
    таблицы, которой реально гейтится текст (урок bans-card.py: 4 копии правил,
    исполняет одна);
  * terminology НЕ дублируется в третий раз — пак указывает на
    hard-bans-card.md (generated, один экран);
  * recently_published и live_slugs парсятся из published-articles-inventory.md,
    а не пересказываются по памяти.

USAGE
    scripts/pack-template.py            # отрендерить файл
    scripts/pack-template.py --check    # exit 1, если файл на диске отстал
    scripts/pack-template.py --stdout   # напечатать, не писать

Exit: 0 ok · 1 stale/--check drift · 2 canon drift (verify-маркер пропал) ·
3 broken setup.
"""
from __future__ import annotations

import argparse
import datetime as _dt
import importlib.util
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "workspace", "seo", "_context-packs",
                   "_stable-fitxpress.yaml")
DETECTOR = os.path.join(REPO, "brand-assets", "style-guides", "scripts",
                        "detect-ai-tells.py")
INVENTORY = os.path.join(REPO, "brand-assets", "content-strategy",
                         "published-articles-inventory.md")

BANNER = ("# GENERATED by scripts/pack-template.py — do not hand-edit.\n"
          "# Re-render: python3 scripts/pack-template.py · staleness gate: --check\n"
          "# context-pack-builder вставляет эти секции в пак VERBATIM и работает только над дельтой темы.")


def _read(rel: str) -> str:
    with open(os.path.join(REPO, rel), encoding="utf-8") as fh:
        return fh.read()


# --------------------------------------------------------------------------
# Стабильные claims. text — формулировка пака; verify — подстроки, которые
# обязаны стоять в канон-файле (нормализованное сравнение по пробелам).
# Канон уехал → рендер падает (exit 2) и называет, что именно.
# --------------------------------------------------------------------------
STABLE_CLAIMS = [
    dict(id="FXS-SPEED",
         text="Two photos (front + side); structured outputs in under 45 seconds.",
         source="proof-points.md, Speed table",
         file="brand-assets/product-info/proof-points.md",
         verify=["Under 45 seconds"]),
    dict(id="FXS-OUTPUTS",
         text="80+ body measurements; body composition outputs: BMI, BMR, fat %, lean mass, fat mass, essential fat, beneficial fat.",
         source="proof-points.md, Output coverage (формулировка строки 'Body composition outputs' дословно)",
         file="brand-assets/product-info/proof-points.md",
         verify=["80+", "fat %, lean mass"],
         note="Всегда «80+ body measurements», никогда «80+ body metrics»; BMI/BMR/composition — calculated metrics/estimates, не measurements (terminology §2.13)."),
    dict(id="FXS-DELIVERY",
         text="Delivered primarily via API/SDK integration directly into the customer's own product or interface; the FitXpress Admin Panel is an optional, complementary interface for monitoring and exporting results, for teams that do not want to build their own dashboard; it does not replace integration.",
         source="overview.md (API and SDK) + решение Вадима на чекпоинте 1 Telehealth Documentation, 2026-09-21",
         file="brand-assets/product-info/overview.md",
         verify=["via API and SDK"],
         note="«monitoring and exporting» — канон с 2026-09-23 (Вадим, Review 1 capture-quality FAQ, C11). Порядок ФИКСИРОВАН Вадимом 2026-09-21: API/SDK — главная история доставки, Admin Panel называется прямо («FitXpress Admin Panel», не «vendor console») и идёт вторым, как опция."),
    dict(id="FXS-ACCURACY",
         text="3DLOOK's measurement accuracy of approximately 96-97% across body metrics, with a typical absolute error of 1.5-2.0 cm per measurement, varying by body part",
         source="accuracy-formulations.md §1.1, verbatim из живой framework-статьи",
         file="brand-assets/product-info/accuracy-formulations.md",
         verify=["96-97%", "1.5-2.0 cm"],
         note="SECONDARY: только если статья реально обсуждает точность. Никогда без условия (референс/популяция/протокол) и без ссылки на framework-статью из того же абзаца. Два бенчмарка (этот и ISO 8559 0.40 cm) не совмещаются в одном абзаце."),
    dict(id="FXS-REPEAT",
         text="For most evaluated measurements, repeated scans showed typical scan-to-scan differences of less than 1 cm",
         source="accuracy-formulations.md §1.2",
         file="brand-assets/product-info/accuracy-formulations.md",
         verify=["less than 1 cm"],
         note="SECONDARY: для longitudinal/repeat-scan тем. Пишется «< 1 cm» / «below 1 cm», locked convention."),
    dict(id="FXS-POPULATION",
         text="FitXpress was not specifically trained on data representing people with physical disabilities, and its measurement performance has not been established for this population. This matters when a disability affects the standard standing pose or capture sequence. In those cases, the program needs a documented alternative measurement path.",
         source="accuracy-formulations.md §5 «Population limitation»; апрув Вадима 2026-09-11",
         file="brand-assets/product-info/accuracy-formulations.md",
         verify=["not specifically trained on data representing people with physical"],
         note="Третье предложение — для workflow-статей (§5 сам так говорит); в остальных берутся первые два. Цифр не несёт."),
    dict(id="FXS-HIPAA",
         text="FitXpress can support HIPAA-governed deployments where 3DLOOK acts as a business associate under an executed BAA, where applicable.",
         source="compliance.md §1, живой trust FAQ",
         file="brand-assets/product-info/compliance.md",
         verify=["business associate under an executed BAA"],
         note="Section-first: короткая заметка + ссылка на FAQ, ответы FAQ не пересказывать. «HIPAA compliant/certified» — hard fail детектора."),
    dict(id="FXS-GDPR",
         text="In most enterprise deployments, the customer acts as the data controller and 3DLOOK acts as the data processor under GDPR.",
         source="compliance.md §2 — каноническое предложение, дословно",
         file="brand-assets/product-info/compliance.md",
         verify=["the customer acts as the data controller and 3DLOOK acts as the data processor under GDPR"],
         note="Не выбрасывать «the data»; хедж «In most enterprise deployments» не срезается."),
    dict(id="FXS-IDS",
         text="Scan records are associated with anonymized, randomly generated IDs; 3DLOOK cannot identify a specific individual from stored scan records.",
         source="compliance.md §4",
         file="brand-assets/product-info/compliance.md",
         verify=["cannot identify a specific individual"]),
    dict(id="FXS-LIFECYCLE",
         text="Submitted data: front/side photos + gender + height + optional weight. Generated data: body measurements, weight/BMI-related outputs, body composition estimates, a 3D model, scan-to-scan comparison outputs. Technical data: capture-quality/pose-validation flags, clothing classification, face-obfuscation confirmation, processing logs with timestamps and request metadata.",
         source="compliance.md §3",
         file="brand-assets/product-info/compliance.md",
         verify=["face-obfuscation", "pose-validation"]),
    dict(id="FXS-RETENTION",
         text="Measurements, body composition data and 3D models are retained on an ongoing basis unless the customer agreement says otherwise; deletion is by scan identifier on the customer's request.",
         source="compliance.md §3/§4",
         file="brand-assets/product-info/compliance.md",
         verify=["retained on an ongoing basis"],
         note="«Processed, not stored» — запрещено: выводы ХРАНЯТСЯ."),
    dict(id="FXS-SCOPE",
         text="Supports: remote intake and body-measurement capture; body composition outputs and Body Progress comparisons; structured data collection for research protocols; structured intake and supporting documentation for customer-managed eligibility workflows; patient/member engagement. Does not independently determine: a diagnosis, treatment, medication recommendation, fitness for duty, employment eligibility, insurance eligibility, clinical-trial eligibility, or any other high-impact individual decision. Final decisions stay with the customer's clinicians, underwriters or other designated decision-makers.",
         source="compliance.md §7",
         file="brand-assets/product-info/compliance.md",
         verify=["Does not independently determine", "Final decisions stay with"],
         note="Канонический boundary-блок («What FitXpress does not do», пункт 7 стандартной структуры about-me.md)."),
    dict(id="FXS-MEDICAL",
         text="FitXpress is not a medical device.",
         source="compliance.md; решение Вадима 2026-09-11 (4-е состояние правила)",
         file="brand-assets/product-info/compliance.md",
         verify=["FitXpress is not a medical device"],
         note="Формулируется прямо; «positioned as» про любой product/intended-use/регуляторный факт — hard fail."),
]

ONELINER_FILE = "brand-assets/product-info/overview.md"
ONELINER_VERIFY = "3DLOOK turns two smartphone photos into a 3D body model and 80+ body measurements in 45 seconds"

BANNED_CLAIMS_STABLE = [
    "most accurate body scanning / best-in-class (без конкретного бенчмарка)",
    "любая цифра точности, сведённая к одному универсальному числу без условия decision/reference/protocol/population/tolerance",
    "medical device / diagnostic / clinical assessment / dosing / prescribing recommendation / eligibility decisioning",
    "replaces DXA (also written DEXA), BIA, calibrated scales, or clinician review",
    "automated eligibility, underwriting, or fraud-detection claims",
    "guaranteed compliance / «makes you compliant» / guaranteed outcomes",
    "любое число не из approved_claims",
    "named competitor comparisons (Prism Labs, Bodygram, Size Stream и др.)",
    "HIPAA compliant / HIPAA certified / SOC 2 certified / FDA-cleared",
    "«no personal identifiers» / «no personal data» — retired 2026-09-18: фото и измерения могут быть персональными данными",
    "«processed, not stored» — выводы хранятся on an ongoing basis",
    "«FitXpress tracks each patient over time» → «the program compares scans it selects» / «scan-to-scan comparison»",
    "«95%+ repeatability consistency» — внутренняя цифра, НЕ публикуется",
]

TONE_BASE = [
    "calm, specific, evidence-led B2B (about-me.md); the reframe move как утверждение, не риторический вопрос (поправка 2026-09-11)",
    "предложения в среднем < 16 слов (article_lint gate 10); декларативно, конкретика над абстракцией",
    "честность про лимиты в одном дыхании с возможностями; actor framing (telehealth program, care team, clinic), не «you»-спам",
    "sensitive verticals (telehealth, GLP-1, insurance, occ health, clinical trials): ранняя scope note курсивом",
]

CLAIMS_DISCIPLINE = [
    "NEVER: diagnose, make treatment/eligibility/clearance decisions, replace clinician/DXA/BIA/calibrated scale, guarantee compliance, auto-detect fraud.",
    "Describe as: a mobile body-scanning solution; a structured body-data capture layer; a remote intake and documentation layer; a workflow-standardization tool; support for review, monitoring, documentation, and operational efficiency (about-me.md verbatim). FitXpress is not a medical device.",
]

TERMINOLOGY_POINTER = (
    "Механические запреты НЕ дублируются здесь (урок bans-card.py: 4 копии правил, исполняет одна). "
    "Писатель читает brand-assets/style-guides/hard-bans-card.md (generated, один экран, не может "
    "разойтись с детектором). Судейские строки — corrective negation, we/our, you, buyer/customer, "
    "ярлыки контент-плана в заголовках — остаются в terminology-guardrails.md за редактором.")


def load_banned_words() -> list[str]:
    spec = importlib.util.spec_from_file_location("detect_ai_tells", DETECTOR)
    mod = importlib.util.module_from_spec(spec)
    sys.modules["detect_ai_tells"] = mod
    spec.loader.exec_module(mod)
    pats = mod.HARD_EN.get("banned_words", [])
    out, pat = [], re.compile(r"\\b([a-z][a-z' -]*?)(?:\(([a-z|]+)\)(\??))?\\b\Z")
    for p in pats:
        m = pat.fullmatch(p)
        if not m:
            continue
        stem, group, optional = m.group(1), m.group(2), m.group(3)
        if group and not optional:
            stem += group.split("|")[0]
        out.append(stem)
    if not out:
        print("detect-ai-tells.py: категория banned_words не дала ни одного слова")
        sys.exit(3)
    return sorted(set(out))


def verify_canon() -> list[str]:
    """Все verify-маркеры против канона. Возвращает список расхождений."""
    drift, cache = [], {}
    def norm(s): return re.sub(r"\s+", " ", s)
    for c in STABLE_CLAIMS:
        body = cache.setdefault(c["file"], norm(_read(c["file"])))
        for marker in c["verify"]:
            if norm(marker) not in body:
                drift.append(f"{c['id']}: «{marker}» больше не найден в {c['file']}")
    if re.sub(r"\s+", " ", ONELINER_VERIFY) not in re.sub(r"\s+", " ", _read(ONELINER_FILE)):
        drift.append(f"company_oneliner: маркер не найден в {ONELINER_FILE}")
    return drift


def parse_inventory():
    """recently_published (30 дней) + live_slugs из verification-таблицы."""
    text = _read("brand-assets/content-strategy/published-articles-inventory.md")
    rows = re.findall(
        r"^\|\s*\d+\s*\|\s*`([^`]+)`\s*\|(.+?)\|\s*\*\*(\d{4}-\d{2}-\d{2})\*\*", text, re.M)
    if not rows:
        print("published-articles-inventory.md: verification-таблица не распарсилась")
        sys.exit(3)
    today = _dt.date.today()
    recent = [(slug, h1.strip(), pub) for slug, h1, pub in rows
              if (today - _dt.date.fromisoformat(pub)).days <= 30]
    return rows, recent


def yq(s: str) -> str:
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def render() -> str:
    drift = verify_canon()
    if drift:
        print("КАНОН УЕХАЛ — stable-файл рендерить нельзя, сначала реши расхождения:")
        for d in drift:
            print("  • " + d)
        sys.exit(2)
    rows, recent = parse_inventory()
    words = load_banned_words()
    L = [BANNER,
         f"# Rendered {_dt.date.today().isoformat()} from: compliance.md, accuracy-formulations.md,",
         "#   proof-points.md, overview.md, detect-ai-tells.py, published-articles-inventory.md",
         "stable_pack_sections:",
         f"  rendered: {_dt.date.today().isoformat()}",
         "  product: fitxpress",
         "",
         f"  company_oneliner: {yq(ONELINER_VERIFY + ', via API and SDK.')}",
         "",
         "  approved_claims_stable:   # вставлять в approved_claims пака как есть; note обязателен рядом с claim"]
    for c in STABLE_CLAIMS:
        L.append(f"    - id: {c['id']}")
        L.append(f"      text: {yq(c['text'])}")
        L.append(f"      source: {yq(c['source'])}")
        if c.get("note"):
            L.append(f"      note: {yq(c['note'])}")
    L += ["", "  banned_claims_stable:"]
    L += [f"    - {yq(b)}" for b in BANNED_CLAIMS_STABLE]
    L += ["", "  banned_words:   # из detect-ai-tells.py (категория banned_words) — единственный исполняемый источник"]
    L += [f"    - {w}" for w in words]
    L += ["", f"  terminology: {yq(TERMINOLOGY_POINTER)}"]
    L += ["", "  tone_base:"]
    L += [f"    - {yq(t)}" for t in TONE_BASE]
    L += ["", "  claims_discipline:"]
    L += [f"    - {yq(t)}" for t in CLAIMS_DISCIPLINE]
    L += ["", "  # из published-articles-inventory.md (live-факты, не план)",
          "  live_slugs:"]
    L += [f"    - {slug}" for slug, _h1, _p in rows]
    L += ["", "  recently_published:   # последние 30 дней на дату рендера"]
    for slug, h1, pub in recent:
        L.append(f"    - {{slug: {slug}, published: \"{pub}\", title: {yq(h1)}}}")
    L.append("")
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--stdout", action="store_true")
    a = ap.parse_args()
    text = render()
    import yaml
    yaml.safe_load(text)   # рендер обязан быть валидным YAML — иначе падаем тут
    if a.stdout:
        print(text)
        return
    if a.check:
        on_disk = _read(os.path.relpath(OUT, REPO)) if os.path.isfile(OUT) else ""
        # даты рендера не считаются дрейфом: сравниваем без них
        strip = lambda s: "\n".join(l for l in s.splitlines()
                                    if not l.startswith(("# Rendered", "  rendered:")))
        if strip(on_disk) != strip(text):
            print("stable-файл отстал: python3 scripts/pack-template.py")
            sys.exit(1)
        print("✅ _stable-fitxpress.yaml актуален")
        return
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"💾 {os.path.relpath(OUT, REPO)} · claims {len(STABLE_CLAIMS)} · "
          f"banned_words {len(load_banned_words())} · live_slugs из инвентаря")


if __name__ == "__main__":
    main()
