#!/usr/bin/env python3
"""split-linkedin-prompts.py — derive one file per LinkedIn profile from the master.

WHY
---
`brand-assets/linkedin-post-prompts.md` is the offline copy of Vadim's Google Doc
and stays the source of truth. But it holds all six profiles at once, and
`post-drafter` is told to read it for every `linkedin-*` post: 11.8KB (~3K tokens)
loaded nine times a pack to use one sixth of it. Worse for prefix caching, the
per-profile read lands early in the drafter's context, so nine drafters that would
otherwise share a cache prefix diverge at their second tool call.

So each profile gets `brand-assets/linkedin-prompts/<profile>.md` containing the
shared rules, the personal-profile rules if it is one of the five people, and its
own section. These files are GENERATED. Editing one is a
change that the next run of this script silently reverts, which is the same drift
that cost this repo the SOUL rewrite and four SEO agents. Edit the master, then
run this.

`--check` compares what is on disk against what the master would produce and exits
1 on any difference, so a cron or a pre-run step catches an edited derivative or a
master that moved on without a re-split.

USAGE
    scripts/split-linkedin-prompts.py            # write
    scripts/split-linkedin-prompts.py --check    # verify, exit 1 on drift
"""
from __future__ import annotations

import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PROJ = os.path.dirname(HERE)
MASTER = os.path.join(PROJ, "brand-assets", "linkedin-post-prompts.md")
OUTDIR = os.path.join(PROJ, "brand-assets", "linkedin-prompts")

SHARED_HEADS = ("House-rule overrides", "Additional resolutions",
                "Rules that apply to every LinkedIn profile")

# Shared with the five PERSONAL profiles only. `linkedin-company` is a company page:
# it keeps 180-280 words and a corporate register, so handing it the 100-170 word
# ceiling and the "write like a person" rules would be handing it the wrong brief.
# Added 2026-09-04 with the section itself.
PERSONAL_HEADS = ("Rules for the five personal profiles",)
COMPANY_PROFILES = ("linkedin-company",)

HEADER = """<!-- GENERATED by scripts/split-linkedin-prompts.py from
     brand-assets/linkedin-post-prompts.md — do not edit this file.
     Edit the master, then re-run the script. `--check` fails on drift. -->

"""


def sections():
    """(shared, personal_only, per_profile). `shared` goes to all six briefs,
    `personal_only` to the five people."""
    text = open(MASTER, encoding="utf-8", errors="replace").read()
    shared, personal, per = [], [], {}
    for chunk in re.split(r"^## ", text, flags=re.M)[1:]:
        head = chunk.splitlines()[0].strip()
        body = "## " + chunk.rstrip() + "\n"
        if head.startswith(SHARED_HEADS):
            shared.append(body)
        if head.startswith(PERSONAL_HEADS):
            personal.append(body)
        m = re.match(r"`(linkedin-[\w-]+)`", head)
        if m:
            per[m.group(1)] = body
    return shared, personal, per


def render(shared, personal, profile, body):
    parts = list(shared)
    if profile not in COMPANY_PROFILES:
        parts += personal
    return HEADER + "\n".join(parts) + "\n" + body


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    p.add_argument("--check", action="store_true")
    a = p.parse_args(argv)

    if not os.path.exists(MASTER):
        print(f"✗ master not found: {MASTER}", file=sys.stderr)
        return 3
    shared, personal, per = sections()
    if not personal:
        print("\u2717 the `Rules for the five personal profiles` section is missing from "
              "the master \u2014 the five people would ship without the length ceiling, "
              "the sentence rule and the location discipline", file=sys.stderr)
        return 3
    if not per:
        print("✗ no `linkedin-*` profile sections found in the master — the heading "
              "format changed; fix this script rather than shipping empty briefs",
              file=sys.stderr)
        return 3

    drift, wrote = [], []
    os.makedirs(OUTDIR, exist_ok=True)
    for profile, body in sorted(per.items()):
        path = os.path.join(OUTDIR, f"{profile}.md")
        want = render(shared, personal, profile, body)
        have = (open(path, encoding="utf-8", errors="replace").read()
                if os.path.exists(path) else None)
        if have == want:
            continue
        if a.check:
            drift.append((profile, "missing" if have is None else "differs from master"))
            continue
        with open(path, "w", encoding="utf-8") as f:
            f.write(want)
        wrote.append(profile)

    # a derivative for a profile the master no longer has
    known = {f"{k}.md" for k in per}
    for name in sorted(os.listdir(OUTDIR)) if os.path.isdir(OUTDIR) else []:
        if name.endswith(".md") and name not in known:
            if a.check:
                drift.append((name, "no longer in the master"))
            else:
                os.remove(os.path.join(OUTDIR, name))
                wrote.append(f"-{name}")

    if a.check:
        if drift:
            for d, why in drift:
                print(f"✗ {d}: {why}")
            print(f"\n{len(drift)} file(s) out of sync — run "
                  "`scripts/split-linkedin-prompts.py`")
            return 1
        print(f"✓ {len(per)} per-profile briefs match the master")
        return 0
    print(f"✓ {len(per)} profile(s) in {os.path.relpath(OUTDIR, PROJ)}"
          + (f" — updated: {', '.join(wrote)}" if wrote else " — already current"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
